# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpbus < Formula
  desc "MCPBus: Turn OpenAPI Spec into MCP Server in Code-mode. MCPBus is a must-have tool for any Agentic AI Developer or Forward Deployed AI Engineer. It is distributed as a stand alone, highly optimized binary, available for all major platforms and OS. Install the binary, run a single command, and get your MCP-server up and running in Code-mode in 1 second. No generated SDKs, no NodeJS, no Python, no VMs.'"
  homepage "https://mcpbus.io"
  version "1.1.21"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.mcpbus.io/releases/v1.1.21/mcpbus_1.1.21_darwin_amd64.tar.gz"
      sha256 "4d346e7a30225531da6a6773d61aed0ed06a379e80e8a124fda75c4256ea3b0f"

      define_method(:install) do
        bin.install "mcpbus"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.mcpbus.io/releases/v1.1.21/mcpbus_1.1.21_darwin_arm64.tar.gz"
      sha256 "68d0e1f95a26544ef319891ecfa7d97ff221c83127535933d602b757072229da"

      define_method(:install) do
        bin.install "mcpbus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://downloads.mcpbus.io/releases/v1.1.21/mcpbus_1.1.21_linux_amd64.tar.gz"
      sha256 "68bf0b14af9d56d529d84ac96f818abbad027e4b2a860702c3d6fb74a57d263a"
      define_method(:install) do
        bin.install "mcpbus"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://downloads.mcpbus.io/releases/v1.1.21/mcpbus_1.1.21_linux_arm.tar.gz"
      sha256 "e12b0e205b302e30fa719d1e4847087f864c864c077d1215644dbd426ad56026"
      define_method(:install) do
        bin.install "mcpbus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://downloads.mcpbus.io/releases/v1.1.21/mcpbus_1.1.21_linux_arm64.tar.gz"
      sha256 "f7050c322474b0372fd8a2d31d376981799186032b0090127dd88c107c27d322"
      define_method(:install) do
        bin.install "mcpbus"
      end
    end
  end
end
